# Generated by Django 3.2.3 on 2021-06-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_cocktailingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.URLField(),
        ),
    ]
