# Generated by Django 3.2.3 on 2021-06-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210602_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=0, max_length=640),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='inventory',
            field=models.ManyToManyField(blank=True, to='backend.Ingredient'),
        ),
    ]
