# Generated by Django 3.2.3 on 2021-05-30 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='cocktailingredient',
            name='cocktail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.cocktail'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='kind',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
