# Generated by Django 3.2.3 on 2021-05-30 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210530_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktailingredient',
            name='cocktail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.cocktail'),
        ),
    ]
