# Generated by Django 3.2.3 on 2021-06-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_cocktailingredient_cocktail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktailingredient',
            name='amount',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
